### ISSUE TITLE
Action默认不开启

### ISSUE THREAD

**Issue by ryuzheng** [AlanDecode/Blog-With-GitHub-Boilerplate#1]
![image](https://user-images.githubusercontent.com/5512323/71140363-0120b100-224c-11ea-8099-ef7a356ce08f.png)

可能因为fork的原因，github默认不启动已设置好的ci.yml的action，不知道是不是只有我遇到这种情况

**Comment by AlanDecode** [comment]
这个提示出现在哪里？点击 Actions 按钮进去以后吗

**Comment by ryuzheng** [comment]
> 这个提示出现在哪里？点击 Actions 按钮进去以后吗

是的，发现做到加secret，更新conf.py后没有更新，然后点进去action按钮，就会有这个提示，点I understand 。。。后，就会开启action，但是是空的，然后我将ci.yml删除一个空行，push之后，action才生效

**Comment by AlanDecode** [comment]
好的
