### ISSUE TITLE
使用 Github desktop发布文章， 每次 Push 前都需要 Pull  cache\info

### ISSUE THREAD

**Issue by ghost** [AlanDecode/Blog-With-GitHub-Boilerplate#10]
![Snipaste_2020-01-06_09-10-53](https://user-images.githubusercontent.com/55862635/71789240-cd73c280-3064-11ea-9341-24462101af6c.png)
![Snipaste_2020-01-06_09-04-50](https://user-images.githubusercontent.com/55862635/71789243-d1074980-3064-11ea-835a-2b24e8467c78.png)

**Comment by AlanDecode** [comment]
update_site.bat already does that for you.
