### ISSUE TITLE
site logo doesn't work

### ISSUE THREAD

**Issue by stormycloudy** [AlanDecode/Blog-With-GitHub-Boilerplate#13]
Hi Alan,

No matter how I tried, I found the site_logo line in conf.py wouldn't work.
And in fact it didn't work in your sample website.
Can you please help me look into this issue?

Many thanks.

**Comment by AlanDecode** [comment]
It works just fine. If you mean your logo does not show on index page, well, the template (Galileo) is designed this way.

**Comment by stormycloudy** [comment]
> It works just fine. If you mean your logo does not show on index page, well, the template (Galileo) is designed this way.

No. I meant the favicon logo doesn't show on the tab. It doesn't show on your sample website, but it does show on your real personal website.

**Comment by AlanDecode** [comment]
favicon is different from logo. You need to provide one in src/static, and add proper meta tag in head_addon setting.
