### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by ghost** [AlanDecode/Blog-With-GitHub-Boilerplate#14]
![Snipaste_2020-01-07_12-13-20](https://user-images.githubusercontent.com/55862635/71867958-37649880-3147-11ea-8a5b-ce2db883c0b3.png)

**Comment by AlanDecode** [comment]
20190111-使用Gatsby.js作为Ghost的前端.md 这篇文章中的代码块指定的语言是 `file:`。没有这种语言所以报错。
在指责别人的 bug 之前，请先确认是否自己的问题。

**Comment by ghost** [comment]
sorry, 请问在哪里查找错误
