### ISSUE TITLE
github SSL 失效造成个人博客无法打开？

### ISSUE THREAD

**Issue by mikamichael** [AlanDecode/Blog-With-GitHub-Boilerplate#19]
你好AlanDecode，请问今天发现github证书失效，导致网站无法访问。请问是否有解决办法？

**Comment by AlanDecode** [comment]
这…恐怕得等 GitHub 处理了。或者你自己套一层 CDN…

**Comment by mikamichael** [comment]
今天下午访问你的那个网站，没有问题，请问其他服务器可以用Maverick搭建个人博客吗？特别喜欢这个风格

**Comment by AlanDecode** [comment]
完全可以啊，Maverick 生成的内容可以上传到任何服务器上，毕竟都是静态文件。

**Comment by mikamichael** [comment]
有具体的教程吗？现在不太懂Maverick的运行原理。
