### ISSUE TITLE
网站logo加载不出来

### ISSUE THREAD

**Issue by qianmianyao** [AlanDecode/Blog-With-GitHub-Boilerplate#21]
```${static_prefix}logo.png```
参数是默认的，没法加载logo
改成下面这样也是无法加载
```./src/static/logo.png```

**Comment by crazydogen** [comment]
- conf.py 注释或删掉template 部分
- 另外在./src/static 提供一个favicon.ico (png2ico)

**Comment by meowdan** [comment]
我也有这个问题，已经注释掉template部分了，试了改成ico的文件也还是不行。。
