### ISSUE TITLE
New post and site 404

### ISSUE THREAD

**Issue by stormycloudy** [AlanDecode/Blog-With-GitHub-Boilerplate#24]
Hi Alan!

我已经使用这个repo来维护自己的站点有一段时间了。很好用！非常感谢！
我之前一直是fork这个repo然后自己做些更改然后post博客。然后之前突然意识到我并不会pull request upstream让你merge，所以以为从你的original repo detach开来是一个更好的选择（？）结果我detach之后，发现在src里加文章，整个站子都404了。请问有什么我可以做吗？我对branch和fork不太熟，不好意思。
谢谢！

**Comment by AlanDecode** [comment]
fork 了之后其实就跟原仓库没啥关系了，不必再进行别的什么操作。你那边可能是没有开启 pages 服务，去仓库设置里看看。

**Comment by stormycloudy** [comment]
> fork 了之后其实就跟原仓库没啥关系了，不必再进行别的什么操作。你那边可能是没有开启 pages 服务，去仓库设置里看看。

我发现detach之后page building自动变成source branch了，换成gh-pages branch之后网页出现了，然而最近的几篇blog都消失了，只剩第一次initial push的一篇。我确认pages 服务是开启的。

**Comment by AlanDecode** [comment]
你应该换成 master 分支，而不是 gh-pages。

**Comment by stormycloudy** [comment]
> 你应该换成 master 分支，而不是 gh-pages。

试过了，可以了！谢谢您！
