### ISSUE TITLE
action运行后会删掉cname

### ISSUE THREAD

**Issue by snipersteve** [AlanDecode/Blog-With-GitHub-Boilerplate#3]
然后设置的自定义域名就失效了。

**Comment by AlanDecode** [comment]
看清楚 CNAME 放的位置。

**Comment by snipersteve** [comment]
cname是放在gh-pages分支下的，action生成的文件也是在这个分支下

**Comment by AlanDecode** [comment]
那你再看看说明里怎么写的呢？
![](https://user-images.githubusercontent.com/28399641/71430904-7affe100-2709-11ea-9fe0-6acad7603960.png)

**Comment by snipersteve** [comment]
sorry 看得不仔细
谢谢！
