### ISSUE TITLE
Fork 之后，404 ~

### ISSUE THREAD

**Issue by ghost** [AlanDecode/Blog-With-GitHub-Boilerplate#9]
http://xiyizhou.github.io/Blog-With-GitHub-Boilerplate/

**Comment by AlanDecode** [comment]
升级 Maverick 或者重新 fork。

**Comment by ghost** [comment]
重新 fork 依旧无效

**Comment by AlanDecode** [comment]
你并没有开启与运行 GitHub Actions，请读说明

**Comment by ghost** [comment]
把 第三步 GitHub Actions 说明，放第一步嘛
